a = int(input("Enter the 1 value: "))
b = int(input("Enter the 2 value: "))
print("Addition: ",a+b)
print("Subtraction: ",a-b)
print("Muliplication: ",a*b)
print("Division: ",a/b)
print("Floor Division:",a//b)
print("Modulo",a%b)
print("Exponential: ",a**b)