a = int(input("Enter the 1st value: "))
b = int(input("Enter the 2nd value: "))
a = b  
print("Assign (=):", a)
a += b
print("Add & Assign (+=):", a)
a -= b
print("Subtract & Assign (-=):", a)
a *= b
print("Multiply & Assign (*=):", a)
a /= b
print("Divide & Assign (/=):", a)
a //= b
print("Floor Divide & Assign (//=):", a)
a %= b
print("Modulus & Assign (%=):", a)
a **= b
print("Exponentiate & Assign (**=):", a)
